#!/bin/sh

( cat <<EOF
;; Alist of (BUILT-IN-SYMBOL . "C-VARIABLE-NAME")
;; All C names must have sym_ prefixed to them

(
EOF
  grep DEFSYM *.c \
    | sed -e 's/^.*DEFSYM(\(.*\), "\(.*\)").*$/(\2 . "\1")/'
  printf ")" )
